### ISSUE TITLE
Create Component Workflow

### ISSUE THREAD

**Issue by phoban01** [open-component-model/vscode-ocm-tools#24]
It should be possible to create components directly from VS Code.

**Comment by In-Ko** [comment]
@jmickey : Has anything already happened here ? If not, I suppose we do not start to work on this, as I would rate the whole MPAS story to be higher in terms of priority.
Back when we discussed the vscode extension, we already said that the READ-ONLY stuff is more important than WRITE for the extension. Maybe we should just reach the MVP for all the read actions, and leave everything else for now.
