### ISSUE TITLE
Improve UX by adding loading indicator

### ISSUE THREAD

**Issue by MeikelVielhauer** [open-component-model/vscode-ocm-tools#49]
Improve the UX when clicking e.g. on a component version in the "component repositories" tree in order to load it.
Currently, I am not getting any feedback when a component version is loaded until its yaml file appears in the vs code window.
A loading indicator for gathering the component version yaml would improve the UX.

**Comment by robertwol** [comment]
@jmickey could you evaluate?

**Comment by jmickey** [comment]
Think I have found a solution for this
